//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionProgress
    {
        public int ActionProgressID { get; set; }
        public Nullable<int> ActionID { get; set; }
        public Nullable<decimal> ActionProgress1 { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
    
        public virtual MitigationsAction MitigationsAction { get; set; }
    }
}
