//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionApproval
    {
        public int ActionID { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> SubDeptId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> SubDivId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> SubBranchId { get; set; }
        public Nullable<int> BizUnitId { get; set; }
        public string JobTitle { get; set; }
        public Nullable<System.DateTime> ApprovelDate { get; set; }
        public Nullable<bool> LastApproval { get; set; }
        public Nullable<bool> IsReadonly { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual MitigationsAction MitigationsAction { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
