//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AskrindoEntities : DbContext
    {
        public AskrindoEntities()
            : base("name=AskrindoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CauseGroup> CauseGroups { get; set; }
        public virtual DbSet<Cause> Causes { get; set; }
        public virtual DbSet<CauseType> CauseTypes { get; set; }
        public virtual DbSet<EffectGroup> EffectGroups { get; set; }
        public virtual DbSet<Effect> Effects { get; set; }
        public virtual DbSet<EffectType> EffectTypes { get; set; }
        public virtual DbSet<RiskGroup> RiskGroups { get; set; }
        public virtual DbSet<RiskType> RiskTypes { get; set; }
        public virtual DbSet<Dept> Depts { get; set; }
        public virtual DbSet<BranchClass> BranchClasses { get; set; }
        public virtual DbSet<ProbLevel> ProbLevels { get; set; }
        public virtual DbSet<ImpactLevel> ImpactLevels { get; set; }
        public virtual DbSet<ImpactCat> ImpactCats { get; set; }
        public virtual DbSet<ImpactDetail> ImpactDetails { get; set; }
        public virtual DbSet<ImpactType> ImpactTypes { get; set; }
        public virtual DbSet<MitigationCat> MitigationCats { get; set; }
        public virtual DbSet<MitigationType> MitigationTypes { get; set; }
        public virtual DbSet<UserInfo> UserInfos { get; set; }
        public virtual DbSet<SerialNumber> SerialNumbers { get; set; }
        public virtual DbSet<Freq> Freqs { get; set; }
        public virtual DbSet<RiskProb> RiskProbs { get; set; }
        public virtual DbSet<RiskImpact> RiskImpacts { get; set; }
        public virtual DbSet<RiskNonMoneyImpact> RiskNonMoneyImpacts { get; set; }
        public virtual DbSet<RiskAttachment> RiskAttachments { get; set; }
        public virtual DbSet<RiskApproval> RiskApprovals { get; set; }
        public virtual DbSet<MitigationAttachment> MitigationAttachments { get; set; }
        public virtual DbSet<SubDept> SubDepts { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<SubDiv> SubDivs { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<SubBranch> SubBranches { get; set; }
        public virtual DbSet<BizUnit> BizUnits { get; set; }
        public virtual DbSet<ImpactRef> ImpactRefs { get; set; }
        public virtual DbSet<RiskState> RiskStates { get; set; }
        public virtual DbSet<RiskLevel> RiskLevels { get; set; }
        public virtual DbSet<MitigationApproval> MitigationApprovals { get; set; }
        public virtual DbSet<RiskMitigation> RiskMitigations { get; set; }
        public virtual DbSet<HelpDoc> HelpDocs { get; set; }
        public virtual DbSet<HelpMenu> HelpMenus { get; set; }
        public virtual DbSet<RiskEvent> RiskEvents { get; set; }
        public virtual DbSet<MitigationUnit> MitigationUnits { get; set; }
        public virtual DbSet<bisni> bisnis { get; set; }
        public virtual DbSet<bisnis_aktifitas> bisnis_aktifitas { get; set; }
        public virtual DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public virtual DbSet<ActionApproval> ActionApprovals { get; set; }
        public virtual DbSet<ActionProgress> ActionProgresses { get; set; }
        public virtual DbSet<MitigationsAction> MitigationsActions { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<KlasifikasiKerugian> KlasifikasiKerugians { get; set; }
        public virtual DbSet<Korwil> Korwils { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<LossEvent> LossEvents { get; set; }
        public virtual DbSet<Risk> Risks { get; set; }
        public virtual DbSet<RiskCat> RiskCats { get; set; }
        public virtual DbSet<RiskCause> RiskCauses { get; set; }
        public virtual DbSet<RiskCauseLine> RiskCauseLines { get; set; }
        public virtual DbSet<RiskEffectLine> RiskEffectLines { get; set; }
        public virtual DbSet<KRINonInvest> KRINonInvests { get; set; }
        public virtual DbSet<KRIInvest> KRIInvests { get; set; }
        public virtual DbSet<KRINonInvestParameter> KRINonInvestParameters { get; set; }
        public virtual DbSet<KRIInvestParameter> KRIInvestParameters { get; set; }
        public virtual DbSet<KRINonInvestData> KRINonInvestDatas { get; set; }
        public virtual DbSet<KRIInvestData> KRIInvestDatas { get; set; }
        public virtual DbSet<LossEventKantorView> LossEventKantorViews { get; set; }
        public virtual DbSet<LossEventPemilikView> LossEventPemilikViews { get; set; }
        public virtual DbSet<LossEventTahunView> LossEventTahunViews { get; set; }
        public virtual DbSet<LossEventBulanView> LossEventBulanViews { get; set; }
        public virtual DbSet<SRNonInvest> SRNonInvests { get; set; }
        public virtual DbSet<SRNonInvestProgress> SRNonInvestProgresses { get; set; }
        public virtual DbSet<SRNIProgressAction> SRNIProgressActions { get; set; }
        public virtual DbSet<KRIRisk> KRIRisks { get; set; }
        public virtual DbSet<KRIRiskCauseLine> KRIRiskCauseLines { get; set; }
        public virtual DbSet<KRIRiskEffectLine> KRIRiskEffectLines { get; set; }
        public virtual DbSet<KRIRiskAttachment> KRIRiskAttachments { get; set; }
        public virtual DbSet<KRIRiskApproval> KRIRiskApprovals { get; set; }
        public virtual DbSet<KRIRiskMitigation> KRIRiskMitigations { get; set; }
        public virtual DbSet<KRIMitigationAttachment> KRIMitigationAttachments { get; set; }
        public virtual DbSet<KRIMitigationApproval> KRIMitigationApprovals { get; set; }
        public virtual DbSet<KRIMitigationAction> KRIMitigationActions { get; set; }
        public virtual DbSet<KRIActionProgress> KRIActionProgresses { get; set; }
        public virtual DbSet<KRIActionApproval> KRIActionApprovals { get; set; }
        public virtual DbSet<KRIRiskProb> KRIRiskProbs { get; set; }
        public virtual DbSet<KRIRiskImpact> KRIRiskImpacts { get; set; }
        public virtual DbSet<KRIRiskNonMoneyImpact> KRIRiskNonMoneyImpacts { get; set; }
        public virtual DbSet<SRInvest> SRInvests { get; set; }
        public virtual DbSet<SRInvestProgress> SRInvestProgresses { get; set; }
        public virtual DbSet<SRIProgressAction> SRIProgressActions { get; set; }
    
        public virtual ObjectResult<RisikoBerulangKantorCabang_Result> RisikoBerulangKantorCabang(Nullable<System.DateTime> tglSebelumAwal, Nullable<System.DateTime> tglSebelumAkhir, Nullable<System.DateTime> tglBerjalanAwal, Nullable<System.DateTime> tglBerjalanAkhir)
        {
            var tglSebelumAwalParameter = tglSebelumAwal.HasValue ?
                new ObjectParameter("TglSebelumAwal", tglSebelumAwal) :
                new ObjectParameter("TglSebelumAwal", typeof(System.DateTime));
    
            var tglSebelumAkhirParameter = tglSebelumAkhir.HasValue ?
                new ObjectParameter("TglSebelumAkhir", tglSebelumAkhir) :
                new ObjectParameter("TglSebelumAkhir", typeof(System.DateTime));
    
            var tglBerjalanAwalParameter = tglBerjalanAwal.HasValue ?
                new ObjectParameter("TglBerjalanAwal", tglBerjalanAwal) :
                new ObjectParameter("TglBerjalanAwal", typeof(System.DateTime));
    
            var tglBerjalanAkhirParameter = tglBerjalanAkhir.HasValue ?
                new ObjectParameter("TglBerjalanAkhir", tglBerjalanAkhir) :
                new ObjectParameter("TglBerjalanAkhir", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RisikoBerulangKantorCabang_Result>("RisikoBerulangKantorCabang", tglSebelumAwalParameter, tglSebelumAkhirParameter, tglBerjalanAwalParameter, tglBerjalanAkhirParameter);
        }
    
        public virtual ObjectResult<RisikoBerulangKantorPusat_Result> RisikoBerulangKantorPusat(Nullable<System.DateTime> tglSebelumAwal, Nullable<System.DateTime> tglSebelumAkhir, Nullable<System.DateTime> tglBerjalanAwal, Nullable<System.DateTime> tglBerjalanAkhir)
        {
            var tglSebelumAwalParameter = tglSebelumAwal.HasValue ?
                new ObjectParameter("TglSebelumAwal", tglSebelumAwal) :
                new ObjectParameter("TglSebelumAwal", typeof(System.DateTime));
    
            var tglSebelumAkhirParameter = tglSebelumAkhir.HasValue ?
                new ObjectParameter("TglSebelumAkhir", tglSebelumAkhir) :
                new ObjectParameter("TglSebelumAkhir", typeof(System.DateTime));
    
            var tglBerjalanAwalParameter = tglBerjalanAwal.HasValue ?
                new ObjectParameter("TglBerjalanAwal", tglBerjalanAwal) :
                new ObjectParameter("TglBerjalanAwal", typeof(System.DateTime));
    
            var tglBerjalanAkhirParameter = tglBerjalanAkhir.HasValue ?
                new ObjectParameter("TglBerjalanAkhir", tglBerjalanAkhir) :
                new ObjectParameter("TglBerjalanAkhir", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RisikoBerulangKantorPusat_Result>("RisikoBerulangKantorPusat", tglSebelumAwalParameter, tglSebelumAkhirParameter, tglBerjalanAwalParameter, tglBerjalanAkhirParameter);
        }
    
        public virtual ObjectResult<RisikoBerulangRisikoUtama_Result> RisikoBerulangRisikoUtama(Nullable<System.DateTime> tglSebelumAwal, Nullable<System.DateTime> tglSebelumAkhir, Nullable<System.DateTime> tglBerjalanAwal, Nullable<System.DateTime> tglBerjalanAkhir)
        {
            var tglSebelumAwalParameter = tglSebelumAwal.HasValue ?
                new ObjectParameter("TglSebelumAwal", tglSebelumAwal) :
                new ObjectParameter("TglSebelumAwal", typeof(System.DateTime));
    
            var tglSebelumAkhirParameter = tglSebelumAkhir.HasValue ?
                new ObjectParameter("TglSebelumAkhir", tglSebelumAkhir) :
                new ObjectParameter("TglSebelumAkhir", typeof(System.DateTime));
    
            var tglBerjalanAwalParameter = tglBerjalanAwal.HasValue ?
                new ObjectParameter("TglBerjalanAwal", tglBerjalanAwal) :
                new ObjectParameter("TglBerjalanAwal", typeof(System.DateTime));
    
            var tglBerjalanAkhirParameter = tglBerjalanAkhir.HasValue ?
                new ObjectParameter("TglBerjalanAkhir", tglBerjalanAkhir) :
                new ObjectParameter("TglBerjalanAkhir", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RisikoBerulangRisikoUtama_Result>("RisikoBerulangRisikoUtama", tglSebelumAwalParameter, tglSebelumAkhirParameter, tglBerjalanAwalParameter, tglBerjalanAkhirParameter);
        }
    
        public virtual ObjectResult<RisikoBerulangSebabUtama_Result> RisikoBerulangSebabUtama(Nullable<System.DateTime> tglSebelumAwal, Nullable<System.DateTime> tglSebelumAkhir, Nullable<System.DateTime> tglBerjalanAwal, Nullable<System.DateTime> tglBerjalanAkhir)
        {
            var tglSebelumAwalParameter = tglSebelumAwal.HasValue ?
                new ObjectParameter("TglSebelumAwal", tglSebelumAwal) :
                new ObjectParameter("TglSebelumAwal", typeof(System.DateTime));
    
            var tglSebelumAkhirParameter = tglSebelumAkhir.HasValue ?
                new ObjectParameter("TglSebelumAkhir", tglSebelumAkhir) :
                new ObjectParameter("TglSebelumAkhir", typeof(System.DateTime));
    
            var tglBerjalanAwalParameter = tglBerjalanAwal.HasValue ?
                new ObjectParameter("TglBerjalanAwal", tglBerjalanAwal) :
                new ObjectParameter("TglBerjalanAwal", typeof(System.DateTime));
    
            var tglBerjalanAkhirParameter = tglBerjalanAkhir.HasValue ?
                new ObjectParameter("TglBerjalanAkhir", tglBerjalanAkhir) :
                new ObjectParameter("TglBerjalanAkhir", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RisikoBerulangSebabUtama_Result>("RisikoBerulangSebabUtama", tglSebelumAwalParameter, tglSebelumAkhirParameter, tglBerjalanAwalParameter, tglBerjalanAkhirParameter);
        }
    
        public virtual ObjectResult<RisikoBerulangTingkatRisiko_Result> RisikoBerulangTingkatRisiko(Nullable<System.DateTime> tglSebelumAwal, Nullable<System.DateTime> tglSebelumAkhir, Nullable<System.DateTime> tglBerjalanAwal, Nullable<System.DateTime> tglBerjalanAkhir)
        {
            var tglSebelumAwalParameter = tglSebelumAwal.HasValue ?
                new ObjectParameter("TglSebelumAwal", tglSebelumAwal) :
                new ObjectParameter("TglSebelumAwal", typeof(System.DateTime));
    
            var tglSebelumAkhirParameter = tglSebelumAkhir.HasValue ?
                new ObjectParameter("TglSebelumAkhir", tglSebelumAkhir) :
                new ObjectParameter("TglSebelumAkhir", typeof(System.DateTime));
    
            var tglBerjalanAwalParameter = tglBerjalanAwal.HasValue ?
                new ObjectParameter("TglBerjalanAwal", tglBerjalanAwal) :
                new ObjectParameter("TglBerjalanAwal", typeof(System.DateTime));
    
            var tglBerjalanAkhirParameter = tglBerjalanAkhir.HasValue ?
                new ObjectParameter("TglBerjalanAkhir", tglBerjalanAkhir) :
                new ObjectParameter("TglBerjalanAkhir", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RisikoBerulangTingkatRisiko_Result>("RisikoBerulangTingkatRisiko", tglSebelumAwalParameter, tglSebelumAkhirParameter, tglBerjalanAwalParameter, tglBerjalanAkhirParameter);
        }
    }
}
