//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bisnis_aktifitas
    {
        public int aktifitasid { get; set; }
        public Nullable<int> bisnisid { get; set; }
        public string aktifitas { get; set; }
    
        public virtual bisni bisni { get; set; }
    }
}
