//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.SubBranches = new HashSet<SubBranch>();
            this.BizUnits = new HashSet<BizUnit>();
            this.UserInfos = new HashSet<UserInfo>();
        }
    
        public int BranchId { get; set; }
        public int DeptId { get; set; }
        public string BranchName { get; set; }
        public int ClassId { get; set; }
        public string BranchCode { get; set; }
        public bool IsSupporting { get; set; }
        public Nullable<int> KorwilId { get; set; }
    
        public virtual Dept Dept { get; set; }
        public virtual BranchClass BranchClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubBranch> SubBranches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BizUnit> BizUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInfo> UserInfos { get; set; }
    }
}
