//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelpDoc
    {
        public int DocId { get; set; }
        public int MenuId { get; set; }
        public string DocName { get; set; }
        public string Description { get; set; }
        public string DocInfo { get; set; }
        public bool IsVisible { get; set; }
        public string Filename { get; set; }
        public string ContentType { get; set; }
        public Nullable<int> ContentLength { get; set; }
        public byte[] Data { get; set; }
    
        public virtual HelpMenu HelpMenu { get; set; }
    }
}
