//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpactRef
    {
        public int ImpactRefId { get; set; }
        public decimal MaxMoney { get; set; }
        public decimal HQPct { get; set; }
        public decimal Branch1Pct { get; set; }
        public decimal Branch2Pct { get; set; }
        public decimal Branch3Pct { get; set; }
        public decimal BizUnitPct { get; set; }
        public decimal SupportingHQPct { get; set; }
        public decimal SupportingBranchPct { get; set; }
        public decimal SupportingBizUnitPct { get; set; }
    }
}
