//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpactLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImpactLevel()
        {
            this.ImpactDetails = new HashSet<ImpactDetail>();
            this.RiskImpacts = new HashSet<RiskImpact>();
            this.RiskNonMoneyImpacts = new HashSet<RiskNonMoneyImpact>();
            this.RiskStates = new HashSet<RiskState>();
            this.RiskMitigations = new HashSet<RiskMitigation>();
            this.MitigationsActions = new HashSet<MitigationsAction>();
            this.Risks = new HashSet<Risk>();
            this.KRIRiskNonMoneyImpacts = new HashSet<KRIRiskNonMoneyImpact>();
        }
    
        public int ImpactLevelId { get; set; }
        public string ImpactLevelName { get; set; }
        public int PctMin { get; set; }
        public int PctMax { get; set; }
        public decimal MoneyMin { get; set; }
        public decimal MoneyMax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImpactDetail> ImpactDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskImpact> RiskImpacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskNonMoneyImpact> RiskNonMoneyImpacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskState> RiskStates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskMitigation> RiskMitigations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MitigationsAction> MitigationsActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Risk> Risks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KRIRiskNonMoneyImpact> KRIRiskNonMoneyImpacts { get; set; }
    }
}
