//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KRIActionProgress
    {
        public int Id { get; set; }
        public string ActionProgress { get; set; }
        public string RecordDate { get; set; }
        public int KRIMitigationActionId { get; set; }
    
        public virtual KRIMitigationAction KRIMitigationAction { get; set; }
    }
}
