//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KRINonInvestParameter
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Target { get; set; }
        public string Order { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int KRINonInvestId { get; set; }
        public Nullable<decimal> Min1 { get; set; }
        public Nullable<decimal> Max1 { get; set; }
        public decimal Min2 { get; set; }
        public decimal Max2 { get; set; }
        public decimal Min3 { get; set; }
        public decimal Max3 { get; set; }
        public Nullable<decimal> Min4 { get; set; }
        public Nullable<decimal> Max4 { get; set; }
    
        public virtual KRINonInvest KRINonInvest { get; set; }
    }
}
