//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KRIRiskProb
    {
        public int Id { get; set; }
        public int ProbOption { get; set; }
        public string Poisson1 { get; set; }
        public string Poisson2 { get; set; }
        public string Binom1 { get; set; }
        public string Binom2 { get; set; }
        public decimal Approx1 { get; set; }
        public decimal Approx2 { get; set; }
        public decimal Approx3 { get; set; }
        public decimal Compare { get; set; }
        public decimal ProbValue { get; set; }
        public int FreqFreqId { get; set; }
        public int ProbLevelProbLevelId { get; set; }
        public int KRIRiskRiskId { get; set; }
    
        public virtual Freq Freq { get; set; }
        public virtual ProbLevel ProbLevel { get; set; }
        public virtual KRIRisk KRIRisk { get; set; }
    }
}
