//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KRIRiskMitigation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KRIRiskMitigation()
        {
            this.KRIMitigationAttachments = new HashSet<KRIMitigationAttachment>();
            this.KRIMitigationActions = new HashSet<KRIMitigationAction>();
            this.KRIMitigationApprovals = new HashSet<KRIMitigationApproval>();
        }
    
        public int Id { get; set; }
        public string MitigationCode { get; set; }
        public string MitigationName { get; set; }
        public System.DateTime InputDate { get; set; }
        public string MitigationDate { get; set; }
        public string Cost { get; set; }
        public string RiskLevel { get; set; }
        public string LimitDate { get; set; }
        public string ApprovalDate { get; set; }
        public string JobTitle { get; set; }
        public string OrgPos { get; set; }
        public string OrgPosId { get; set; }
        public string IsReadOnly { get; set; }
        public int KRIRiskRiskId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KRIMitigationAttachment> KRIMitigationAttachments { get; set; }
        public virtual KRIRisk KRIRisk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KRIMitigationAction> KRIMitigationActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KRIMitigationApproval> KRIMitigationApprovals { get; set; }
    }
}
