//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KRIRiskCauseLine
    {
        public int Id { get; set; }
        public string CustomCause { get; set; }
        public string Note { get; set; }
        public int CauseCauseId { get; set; }
        public int CauseGroupCauseGroupId { get; set; }
        public int CauseTypeCauseTypeId { get; set; }
        public int KRIRiskRiskId { get; set; }
    
        public virtual Cause Cause { get; set; }
        public virtual CauseGroup CauseGroup { get; set; }
        public virtual CauseType CauseType { get; set; }
        public virtual KRIRisk KRIRisk { get; set; }
    }
}
