//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KRIRiskApproval
    {
        public int Id { get; set; }
        public int KRIRiskRiskId { get; set; }
        public int OrgPos { get; set; }
        public int OrgPosId { get; set; }
        public string OrgName { get; set; }
        public System.DateTime ApprovalDate { get; set; }
        public System.DateTime LimitDate { get; set; }
        public bool LastApproval { get; set; }
        public bool IsReadOnly { get; set; }
        public string JobTitle { get; set; }
        public System.Guid UserInfoUserId { get; set; }
    
        public virtual KRIRisk KRIRisk { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
