//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LossEventTahunView1
    {
        public Nullable<int> tahun { get; set; }
        public string pemilik { get; set; }
        public Nullable<int> id_pemilik { get; set; }
        public string LossEvent { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<decimal> Expr2 { get; set; }
        public int jml_kasus { get; set; }
        public decimal ImpactFinancial { get; set; }
    }
}
