//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MitigationUnit
    {
        public int MitigationUnitId { get; set; }
        public int MitigationId { get; set; }
        public int DivisionId { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual RiskMitigation RiskMitigation { get; set; }
    }
}
