//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MitigationsAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MitigationsAction()
        {
            this.ActionProgresses = new HashSet<ActionProgress>();
        }
    
        public int ActionID { get; set; }
        public Nullable<int> MitigationId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> ProbLevelId { get; set; }
        public Nullable<int> ImpactLevelId { get; set; }
        public Nullable<System.Guid> PIC { get; set; }
        public string ActionCode { get; set; }
        public string ActionName { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string Require { get; set; }
        public Nullable<bool> RKAPF { get; set; }
        public Nullable<int> RiskLevel { get; set; }
        public Nullable<System.DateTime> LimitDate { get; set; }
        public Nullable<bool> IsReadOnly { get; set; }
        public Nullable<decimal> TotalProgress { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> SubDeptId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> SubDivId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> SubBranchId { get; set; }
        public Nullable<int> BizUnitId { get; set; }
        public Nullable<decimal> Biaya { get; set; }
        public string PIC2 { get; set; }
    
        public virtual ProbLevel ProbLevel { get; set; }
        public virtual ImpactLevel ImpactLevel { get; set; }
        public virtual ActionApproval ActionApproval { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionProgress> ActionProgresses { get; set; }
        public virtual RiskMitigation RiskMitigation { get; set; }
    }
}
