//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MitigationApproval
    {
        public int ApprovalId { get; set; }
        public int MitigationId { get; set; }
        public int OrgPos { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> SubDeptId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> SubDivId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> SubBranchId { get; set; }
        public Nullable<int> BizUnitId { get; set; }
        public string OrgName { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string JobTitle { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<System.DateTime> LimitDate { get; set; }
        public bool LastApproval { get; set; }
        public bool IsReadOnly { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual RiskMitigation RiskMitigation { get; set; }
    }
}
