//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    
    public partial class RisikoBerulangRisikoUtama_Result1
    {
        public string RiskCatName { get; set; }
        public int RiskCatId { get; set; }
        public Nullable<int> baru { get; set; }
        public Nullable<int> t_berulang { get; set; }
        public Nullable<int> berulang { get; set; }
        public Nullable<int> total { get; set; }
    }
}
