//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskLevel
    {
        public int LevelId { get; set; }
        public string LevelName { get; set; }
        public int MinValue { get; set; }
        public int MaxValue { get; set; }
        public string Action { get; set; }
        public string BackColor { get; set; }
        public string ForeColor { get; set; }
    }
}
