//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskState
    {
        public int StateId { get; set; }
        public int RiskId { get; set; }
        public Nullable<int> MitigationId { get; set; }
        public System.DateTime StateDate { get; set; }
        public int ProbLevelId { get; set; }
        public int ImpactLevelId { get; set; }
        public int RiskLevel { get; set; }
    
        public virtual ProbLevel ProbLevel { get; set; }
        public virtual ImpactLevel ImpactLevel { get; set; }
    }
}
