//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskImpact
    {
        public int RiskId { get; set; }
        public bool IsMoneyImpact { get; set; }
        public Nullable<decimal> MoneyDirect { get; set; }
        public Nullable<decimal> MoneyIndirect { get; set; }
        public Nullable<int> ImpactLevelId { get; set; }
    
        public virtual ImpactLevel ImpactLevel { get; set; }
    }
}
