//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRInvest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SRInvest()
        {
            this.SRInvestProgresses = new HashSet<SRInvestProgress>();
        }
    
        public int Id { get; set; }
        public string CauseAnalysis { get; set; }
        public string StrategicResponse { get; set; }
        public System.DateTime SubmitDate { get; set; }
        public int KRIInvestDataId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRInvestProgress> SRInvestProgresses { get; set; }
        public virtual KRIInvestData KRIInvestData { get; set; }
    }
}
