//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRInvestProgress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SRInvestProgress()
        {
            this.SRIProgressActions = new HashSet<SRIProgressAction>();
        }
    
        public int Id { get; set; }
        public string PIC { get; set; }
        public string Resources { get; set; }
        public System.DateTime FTargetDate { get; set; }
        public int SRInvestId { get; set; }
        public bool RKAPF { get; set; }
    
        public virtual SRInvest SRInvest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRIProgressAction> SRIProgressActions { get; set; }
    }
}
