//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRNIProgressAction
    {
        public int Id { get; set; }
        public string Detail { get; set; }
        public decimal Progress { get; set; }
        public System.DateTime Tanggal { get; set; }
        public int SRNonInvestProgressId { get; set; }
    
        public virtual SRNonInvestProgress SRNonInvestProgress { get; set; }
    }
}
