//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRNonInvestProgress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SRNonInvestProgress()
        {
            this.SRNIProgressActions = new HashSet<SRNIProgressAction>();
        }
    
        public int Id { get; set; }
        public int SRId { get; set; }
        public string PIC { get; set; }
        public string Resources { get; set; }
        public System.DateTime FTargetDate { get; set; }
        public bool RKAPF { get; set; }
    
        public virtual SRNonInvest SRNonInvest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRNIProgressAction> SRNIProgressActions { get; set; }
    }
}
