//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askrindo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.MitigationApprovals = new HashSet<MitigationApproval>();
            this.ActionApprovals = new HashSet<ActionApproval>();
            this.RiskApprovals = new HashSet<RiskApproval>();
            this.Risks = new HashSet<Risk>();
            this.RiskMitigations = new HashSet<RiskMitigation>();
            this.KRINonInvestDatas = new HashSet<KRINonInvestData>();
            this.KRIInvestDatas = new HashSet<KRIInvestData>();
            this.KRIRiskApprovals = new HashSet<KRIRiskApproval>();
            this.KRIRisks = new HashSet<KRIRisk>();
        }
    
        public System.Guid UserId { get; set; }
        public string FullName { get; set; }
        public string JobTitle { get; set; }
        public bool IsRiskOwner { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> SubDeptId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> SubDivId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> SubBranchId { get; set; }
        public Nullable<int> BizUnitId { get; set; }
        public int OrgPos { get; set; }
        public Nullable<bool> StsPC { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Dept Dept { get; set; }
        public virtual SubDiv SubDiv { get; set; }
        public virtual SubBranch SubBranch { get; set; }
        public virtual BizUnit BizUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MitigationApproval> MitigationApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionApproval> ActionApprovals { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskApproval> RiskApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Risk> Risks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskMitigation> RiskMitigations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KRINonInvestData> KRINonInvestDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KRIInvestData> KRIInvestDatas { get; set; }
        public virtual Division Division { get; set; }
        public virtual SubDept SubDept { get; set; }
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KRIRiskApproval> KRIRiskApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KRIRisk> KRIRisks { get; set; }
    }
}
